### ISSUE TITLE
No data returned for stress score.

### ISSUE THREAD

**Issue by Rojuinex** [Emotiv/insight_sdk#2]
When I run the EmotionalState Demo the stress score is always 0.  I don't think that it is because I am perfectly unstressed, though that would be nice :)

**Comment by LupusDei** [comment]
In the google community they are saying the rear sensor might need some of the saline solution to get measurements, but I too have experienced the same lack of readings on stress.

**Comment by patdotme** [comment]
hi @Rojuinex which platform have you tried, Windows or Mac?
We have discovered some glitches with the stress detection and we are working (stressing) on it - stay tuned. Thanks.

**Comment by Rojuinex** [comment]
@patdotme I'm on a Mac.  I can try my windows box in the morning.

@lupusdei I've also had issues with getting Pz to have a good connection. Unfortunately my headset did not come with the solution so I cannot try it :/

**Comment by patdotme** [comment]
@Rojuinex you can try with normal contact lenses solution ;)
