### ISSUE TITLE
Python example edf_insight_exam.py not working?

### ISSUE THREAD

**Issue by fneitzel** [Emotiv/insight_sdk#4]
What am I missing?

Traceback (most recent call last):
  File "edf_insight_exam.py", line 62, in <module>
    IEE_DataCreate = libEDK.IEE_DataCreate
  File "C:\Python27\lib\ctypes\__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'IEE_DataCreate' not found

**Comment by dhakimdahakim** [comment]
I just tried compiling the C++ code.  It looks like everything IEE_Data is just flat out missing.  As such, main.cpp complains about IEE_DataChannel_t, IEE_DataCreate(), IEE_DataSetBufferSizeInSec, IEE_DataAcquisitionEnable, IEE_DataUpdateHandle, IEE_DataGetNumberOfSample, IEE_DataGet, and IEE_DataFree.  

I'm guessing the python code has the same problems.  Did you find any working examples as of yet?

**Comment by fneitzel** [comment]
Hi @dhakimdahakim 

No, i couldn't manage to get the examples to work yet.
I tried to exhange the dlls with those from the InsightSDKLite-Installer.exe without any success...

**Comment by nguoithichkhampha** [comment]
Sorry @fneitzel @dhakimdahakim, these function isn't included in edk.dll. Only version Premium have them.We will remove it in example.

**Comment by fneitzel** [comment]
@nguoithichkhampha Thank you
@nguoithichkhampha @dhakimdahakim Further I'd like to know, how i can set up the bluetooth-connection between my computer and the insight? i made sure that the computer has bluetooth 4. It is paired with the Insight, but i don't receive any connection in the Emotiv Insight SDK Lite 1.1.1.0. 

Do i need to buy that https://emotiv.com/store/product_9.html (== Dongle?) to receive data via bluetooth from the insight.

annotation: When i tried to connect the Galaxy Tab 3 to the insight it was telling me too, that the devices are paired, but after a while i noticed that the tab3 just has Bluetooth 3.x ...

Please tell me how to set up the connection right.

**Comment by nguoithichkhampha** [comment]
@fneitzel , Our sdk have 2 option to connect with headset: dongle or bluetooth . Emotiv Insight SDK Lite 1.1.1.0 don't have option connect with bluetooth or dongle. You only connect with Composer.

about set up the connection bluetooth is automatic. It is included in SDK. You don't have to set up manually.

Attention: Our device use protocol GATT in Bluetooth Low Energy. It is a part of Bluetooth 4.0. So, may be some devices have bluetooth 4.0 not included bluetooth low energy.

**Comment by fneitzel** [comment]
@dhakimdahakim [...]Emotiv Insight SDK Lite 1.1.1.0 don't have option connect with bluetooth or dongle [...]  Now i'am a little bit confused ...  which SDK i need to install to connect to the Insight?

[...] about set up the connection bluetooth is automatic. It is included in SDK. You don't have to set up manually[...] because i thaught, that ineed to install the SDKLite1.1.1.0 and there will be everything included for setting up the connecting..

**Comment by nguoithichkhampha** [comment]
Did you call function IEE_EngineConnect before call IEE_DataCreate?

SDKLite 1.1.1.0 also don't have option connect with headset. You should use SDK version Standard or Premium to work with our headset.

**Comment by fneitzel** [comment]
Thank's for your request. Yes. So in detail. here is what i do:

I move 'edk.dll','edk_utils.dll' and 'glut32.dll' to the Python example folder.
i 'cd' into that dir.
I remove IEE_DataCreate from the script as you said.
Then i execute the script:

    python edf_insight_exam.py

working with python2.7.10 - 32bit

So the script calls ' connect to emoengine'
    if libEDK.IEE_EngineConnect("Emotiv Systems-5") != 0:
        print "Emotiv Engine start up failed."
        connected = False

I think i did everything as described in the video:
    https://youtu.be/Qv9I8F0wVfI?t=11m00s

-----

If i connect with SDKLite 1.1.1.0 sometimes I'am able to enter a user name and afterwards i see changing the bluetooth connection signal in the software to a 'good/green' signal - but nothing else changes. I have no uptime or any sensor updates.

What's the current SDK Standard version? 
 http://wiki.emotiv.com/tiki-index.php?page=Downloads
 https://emotiv.com/store/app/
----
Where can i find the link to get a Premium license?

Thank you for your efforts.

**Comment by hoangphamemotiv** [comment]
hi @fneitzel. 

Standard version is version in Github. You can get from here: edk standard libs, examples, composer app. 
EEGLogger and edf examples are examples for Premium version. so, you cant run them with edk standard libs. 
for python window, you can get edk libs from : https://github.com/Emotiv/insight_sdk/tree/Insight-beta-release/bin/win32. then pls try with emostate example.
